# Generated by Django 4.2.5 on 2023-09-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delegacias", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consulta",
            new_name="Delegacia",
        ),
    ]
