# Generated by Django 4.2.5 on 2023-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegacias", "0002_rename_consulta_delegacia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delegacia",
            options={"verbose_name": "Delegacia", "verbose_name_plural": "Delegacias"},
        ),
        migrations.RenameField(
            model_name="avaliacao",
            old_name="consulta",
            new_name="delegacia",
        ),
        migrations.AlterField(
            model_name="delegacia",
            name="titulo",
            field=models.DateTimeField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("email", "delegacia")},
        ),
    ]
