# Generated by Django 4.2.5 on 2023-09-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegacias", "0004_alter_delegacia_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegacia",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
