# Generated by Django 4.2.5 on 2023-09-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegacias", "0006_regiao"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegacia",
            name="localizacao",
            field=models.CharField(default="SOME STRING", max_length=140),
        ),
    ]
